on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
      - master
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '27 4 * * *'
name: Semgrep
jobs:
  buildMavenDepTree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven and Write Locks
        run:
          mvn dependency:tree -DoutputFile=maven_dep_tree.txt -Dmaven.test.skip=true
      - name: Create Zip File
        run:
          find . -type f -name 'maven_dep_tree.txt' -exec zip -r archive.zip {} +
      - name: Upload Dependency Zip
        uses: actions/upload-artifact@v3
        with:
            name: zipfile
            path: archive.zip
  semgrep:
    needs: buildMavenDepTree
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from the previous job
        uses: actions/download-artifact@v3
        with:
          name: zipfile
      - name: Semgrep Scan
        run: |
          unzip -o archive.zip
          semgrep ci
